### ISSUE TITLE
Eva Lai | Phraseology

### ISSUE THREAD

**Issue by evalaidc** [ga-dc/project2-gallery#111]
Comfort: 4.5/5

Complete: 5/5

I would like some feedback on the functionality of my application and comments on my user stories. Thanks.

Github Repo: https://github.com/evalaidc/phraseology

Screencast: https://youtu.be/NE47ShCBnEM

Heroku: https://phraseology.herokuapp.com/

**Comment by avalant** [comment]
Feedback left in garnet
