### ISSUE TITLE
Clements-Proj 2

### ISSUE THREAD

**Issue by sdkclements** [ga-dc/project2-gallery#113]
c:4.5
c:4.5

Something with my models / routes is a little buggy and preventing some delete work. Id love feedback where i messed that up.

github: https://github.com/sdkclements/project_2_tv_clone
heroku:  https://project-my-free-tv.herokuapp.com/
youtube: https://youtu.be/npXqSIkVKIQ

**Comment by amaseda** [comment]
:+1: check out this PR: https://github.com/sdkclements/project_2_tv_clone/pull/1
