### ISSUE TITLE
Storyteller (Mike)

### ISSUE THREAD

**Issue by maikelnabil** [ga-dc/project2-gallery#115]
GitHub: https://github.com/maikelnabil/storyteller
Deployed app: https://mike-storyteller.herokuapp.com/
Screencast: https://www.youtube.com/watch?v=Koqdlu7o-2A&feature=youtu.be

Added Facebook log-in.

The deployed version is more advanced than the one on Github. I don't want to push it to GitHub, because it has my secret credentials to third-party log-in.

**Comment by nayana487** [comment]
You can prevent secrets from being added with this: https://github.com/awslabs/git-secrets

see feedback here: https://github.com/maikelnabil/storyteller/pull/1
