### ISSUE TITLE
DeliverWe by Will Hawkins

### ISSUE THREAD

**Issue by hawkins-will** [ga-dc/project2-gallery#122]
Heroku-hosted App: http://deliverwe.herokuapp.com/

GitHub Repo: https://github.com/hawkins-will/DeliverWe

Screencast Demo: https://youtu.be/2rtm1vINb-A

Completeness: 4/5

Comfort: 5/5

Honestly, I felt pretty comfortable with building this app and I didn't cross TOO many issues that derailed me. There's just SO MUCH more that I wanted to add that I'm a little dissatisfied with it. 

Also I'm not crazy about the Styling of it and I'm realizing I have a tendency to really clutter things.

**Comment by nayana487** [comment]
see feedback here: https://github.com/hawkins-will/DeliverWe/pull/1
