### ISSUE TITLE
Recipe Ting! by Nyketha 

### ISSUE THREAD

**Issue by Nykke** [ga-dc/project2-gallery#124]
screencast: https://youtu.be/WjbPQC3L5Fk
heroku: https://recipeting.herokuapp.com/
github: https://github.com/Nykke/Project_02_Recipe_Ting

need a little direction in making the form validations work, I tried and it's picking up on it, it just won't display the message.

**Comment by superbuggy** [comment]
Well done! See my PR for comments. Don't merge it, though, haha.
