### ISSUE TITLE
Garden Buddy - Project 2 - Chris Wightman

### ISSUE THREAD

**Issue by cjwightman** [ga-dc/project2-gallery#127]
YouTube Link: https://youtu.be/eBSw121kG-E
Heroku Link: https://garden-buddy.herokuapp.com/
GitHub Link: https://github.com/cjwightman/project_two

Many features and content yet to be added.

**Comment by nayana487** [comment]
See evaluation here: https://github.com/cjwightman/project_two/pull/1
