### ISSUE TITLE
Dan Lin

### ISSUE THREAD

**Issue by dlin2102** [ga-dc/project2-gallery#128]
Youtube link: https://www.youtube.com/watch?v=ZCgXbDe8bm0

Heroku: https://calm-falls-69808.herokuapp.com/books
It deployed successfully, the only issue was that my uploaded images would appear but disappear some time later.I had to get a s3 account bc of my paperclip gem and when I did that it. It messed everything up. I had to make a ton of changes in the terminal and I'm not sure what I did. I'm trying to undo everything but it's not working so I might scrap the deployed link, git clone my previous commit and make a new deployment.

Github: https://github.com/dlin2102/book_reviews
Look at my local instead

**Comment by AWhitleyGA** [comment]
Really great work 👍 see the PR on your project's Github repo for feedback
