### ISSUE TITLE
Mitchell Carroll- Project 2 

### ISSUE THREAD

**Issue by mitchellcarroll** [ga-dc/project2-gallery#139]
https://obscure-beyond-12569.herokuapp.com/dashboard

https://youtu.be/FX-bBEjoK3I

**Comment by mitchellcarroll** [comment]
https://github.com/mitchellcarroll/project-2

**Comment by AWhitleyGA** [comment]
Really solid work here 👍 please see the PR on the project's Github repository for more detailed feedback
