### ISSUE TITLE
Project 2 | Taylor Scott

### ISSUE THREAD

**Issue by taylorscott91** [ga-dc/project2-gallery#140]
https://github.com/taylorscott91/project2

http://mysterious-scrubland-55112.herokuapp.com/

https://www.youtube.com/watch?v=IK1sk--ZYIA

**Comment by AWhitleyGA** [comment]
Good work, but there are definitely some bugs currently limiting functionality in the app. Please refer to the PR on the project's Github repository for detailed feedback. 👍
