### ISSUE TITLE
Hali Bakarr - Project 2

### ISSUE THREAD

**Issue by utamilah** [ga-dc/project2-gallery#149]
Project Repo: https://github.com/utamilah/khwiki
Deployed App: https://sheltered-wildwood-24413.herokuapp.com/
Screencast: https://www.youtube.com/watch?v=rcipD2lKP_0

**Comment by AWhitleyGA** [comment]
Really great job 👍 please refer to the Pull Request on your project's repo for feedback:
https://github.com/utamilah/khwiki/pull/1
