### ISSUE TITLE
Project-2 by Ick Hyun Kwon

### ISSUE THREAD

**Issue by kwonih1020** [ga-dc/project2-gallery#153]
Github - https://github.com/kwonih1020/Project-2

Heroku - https://secure-hollows-65430.herokuapp.com/users/sign_in

Youtube - https://youtu.be/1mNXZ4mHazA

**Comment by juancgarcia** [comment]
Good job 👍 please refer to the Pull Request on your project's repo for feedback:
kwonih1020/Project-2#1
