### ISSUE TITLE
WPurdum Project 2 Submission

### ISSUE THREAD

**Issue by wjpurdum** [ga-dc/project2-gallery#155]
Repo: https://github.com/wjpurdum/Project2
Screencast: https://www.youtube.com/watch?v=ZYx5KCkDSlI&feature=youtu.be
Heroku: https://bluegrasscollective.herokuapp.com/states/1 
*** My background image is not showing up in my heroku deployment, currently working to get it fixed.

**Comment by wjpurdum** [comment]
The heroku link I sent was not to the index page - please use this one! https://bluegrasscollective.herokuapp.com/users/sign_in

**Comment by juancgarcia** [comment]
Good job 👍 please refer to the Pull Request on your project's repo for feedback:
wjpurdum/Project2#1
