### ISSUE TITLE
Erin Dawson Project 2

### ISSUE THREAD

**Issue by edawson1980** [ga-dc/project2-gallery#158]
Screencast: https://www.youtube.com/watch?v=G7aBS-6x90w&feature=youtu.be

Repo: https://github.com/edawson1980/story-doc

My apologies for the rough screencast...it was intended as a test run, but as I ran into deployment issues this morning I was unable to find the time to do a better one before the submission deadline.

**Comment by jsm13** [comment]
No apologies necessary! I'm enjoying this tremendously

**Comment by edawson1980** [comment]
thanks!
