### ISSUE TITLE
DC Cars and Coffee - Ammar Alasadi

### ISSUE THREAD

**Issue by ammaralasadi1** [ga-dc/project2-gallery#164]
Link to deployed app: https://intense-inlet-16676.herokuapp.com
Link to GitHub repo: https://github.com/ammaralasadi1/Dc-Cars-and-Coffee
Link to Screencast: https://www.youtube.com/watch?v=kMSommZS6ho&t=21s

**Comment by AWhitleyGA** [comment]
Really great job 👍 please see the pull request on your project's repo for feedback:
https://github.com/ammaralasadi1/Dc-Cars-and-Coffee/pull/1
