### ISSUE TITLE
Project 2

### ISSUE THREAD

**Issue by StormyRamsey** [ga-dc/project2-gallery#166]
Hello, 
Towards the end of my project I had to drop my database, as a result I lost some of my CSS attributes and I see I experienced the same problem when pushing to Heroku. 

One question: When I changed my seeds file and after I dropped and remigrated my database I was still able to see the data I delete. Is there a way to correct this without having my previous seeds come up and losing my css settings?

https://guarded-basin-96925.herokuapp.com/

https://youtu.be/Wkk49S7_1tM

https://github.com/StormyRamsey/project_2_mommy_blog

**Comment by juancgarcia** [comment]
Good work. Please refer to the Pull Request on your project's repo for feedback:
https://github.com/StormyRamsey/project_2_mommy_blog/pull/1
