### ISSUE TITLE
Boredmbear - Omar Chaudhry

### ISSUE THREAD

**Issue by o0c91047** [ga-dc/project2-gallery#167]
Github repo https://github.com/o0c91047/project2_boredmbear
screencast https://vid.me/1XAf
deployed app (not working) https://boredmbear.herokuapp.com/

This is a trainwreck. I'll fix this.

**Comment by o0c91047** [comment]
For the love of anything decent please do not let anyone see this.

**Comment by AWhitleyGA** [comment]
Please see the Pull Request on your project repo for detailed feedback:
https://github.com/o0c91047/project2_boredmbear/pull/1

While your code was not functioning, it was on the right track. Additionally, I really liked the clean styling and layout.
