### ISSUE TITLE
Matt's Project 2 - Crowd_Sourced Candidates (VA)

### ISSUE THREAD

**Issue by mattcfilbert** [ga-dc/project2-gallery#186]
Github repo:

https://github.com/mattcfilbert/crowdsourceCandidate

Youtube presenation:

https://youtu.be/GtSWFb527w0

**Comment by AWhitleyGA** [comment]
Great job. Please refer to the Pull Request on your project's repo for feedback. 👍 
https://github.com/mattcfilbert/crowdsourceCandidate/pull/1
