### ISSUE TITLE
Project 2 - Ramen Shaman - Liz Jewell

### ISSUE THREAD

**Issue by lizardbird** [ga-dc/project2-gallery#187]
Project Repo: https://github.com/lizardbird/wdi-proj2-ramen-shaman
Live App: https://ramen-shaman.herokuapp.com/
Screencast: https://youtu.be/TV_shGN4hZQ

**Comment by AWhitleyGA** [comment]
Great job on this project. Please see the Pull Request on your project's repo for feedback:
https://github.com/lizardbird/wdi-proj2-ramen-shaman/pull/3
👍
