### ISSUE TITLE
oiubsdglijhsdlgkjkjbfgkjlhlkjwegdsvc

### ISSUE THREAD

**Issue by perryf** [ga-dc/project2-gallery#191]
Repo: https://github.com/perryf/Star-Wars-Wiki
Heroku: https://star-wars-wiki-perry.herokuapp.com/
Screencast: Almost there...

**Comment by perryf** [comment]
https://youtu.be/FQvVhDZR1jo

**Comment by AWhitleyGA** [comment]
Great job on the project. Please see the Pull Request on your project's repo for feedback:
https://github.com/perryf/Star-Wars-Wiki/pull/1

**Comment by AWhitleyGA** [comment]
P.S. make sure to update your Github repo's `website url` setting with the url of the deployed app
