### ISSUE TITLE
Project 2 Tim Gafvert

### ISSUE THREAD

**Issue by TimGafvert** [ga-dc/project2-gallery#192]
Git Hub:
https://github.com/TimGafvert/Project2

Heroku:
https://codeskillswap.herokuapp.com/

Screencast:
https://www.youtube.com/watch?v=sWD4N5QV2CY&feature=youtu.be

**Comment by juancgarcia** [comment]
Great job! Please refer to the Pull Request on your project's repository for feedback:
https://github.com/TimGafvert/Project2/pull/1
👍
