### ISSUE TITLE
Charles Cox project2

### ISSUE THREAD

**Issue by cwcox** [ga-dc/project2-gallery#196]
[https://youtu.be/C7uxQK-DlUo](https://youtu.be/C7uxQK-DlUo)

[repo](https://github.com/cwcox/fantasy_draft_simulator)

[site](https://ff-draft-sim.herokuapp.com)

**Comment by juancgarcia** [comment]
Great job! Please refer to the Pull Request on your project's repository for feedback:
https://github.com/cwcox/fantasy_draft_simulator/pull/1
👍
