### ISSUE TITLE
Amarinder1 Project 2

### ISSUE THREAD

**Issue by Amarinder1** [ga-dc/project2-gallery#201]
link to app: https://amarinder-amazon.herokuapp.com/

link to repo: https://github.com/Amarinder1/Project2-Amazon

link to screencast: https://www.youtube.com/watch?v=ZudZaK24c_g&feature=youtu.be

**Comment by aspittel** [comment]
🎉  Great job! Feedback here: https://github.com/Amarinder1/Project2-Amazon/pull/1
