### ISSUE TITLE
Angie Spears_ Project 2

### ISSUE THREAD

**Issue by AMSpears** [ga-dc/project2-gallery#218]
Link to Github Repo:
https://github.com/AMSpears/shoppinglist

Link to Video presentation
https://vimeo.com/245181581

Link to deployed app:
https://as-shopping-list.herokuapp.com/lists

**Comment by perryf** [comment]
Nice job on the project Angie!  Please refer to the inline code comments (see Files Changed) and the included feedback.md document for detailed feedback.
