### ISSUE TITLE
Michael Ortiz's project 2

### ISSUE THREAD

**Issue by mortiz01** [ga-dc/project2-gallery#220]
repo: https://git.generalassemb.ly/mortiz01/project_2/tree/master/millysblog

video: https://www.youtube.com/watch?v=P9woKP79OOg

heroku app: http://millysblog.herokuapp.com/

**Comment by perryf** [comment]
Good job Michael.  Please refer to the inline code comments (see Files Changed) and the included feedback.md document for detailed feedback.
👍
