### ISSUE TITLE
Dan McQuade - Project 2

### ISSUE THREAD

**Issue by danmcquade** [ga-dc/project2-gallery#223]
GitHub Repository:
https://github.com/danmcquade/photos-on-rails

Heroku Deployment:
http://photos-on-rails.herokuapp.com/

Screencast:
https://youtu.be/sFoV5U_Gyc0

**Comment by ZakkMan** [comment]
Hey @danmcquade, you can find the pull request with my feedback here: https://github.com/danmcquade/photos-on-rails/pull/1

Great job on your project! It's clear you worked hard on it!

Thanks,
Zakk
