### ISSUE TITLE
Ante Bozic Project 2

### ISSUE THREAD

**Issue by antebozic** [ga-dc/project2-gallery#227]
https://youtu.be/tPFD5NPyqRc

At the time of posting this issue, I'm having an error with Heroku deployment of the app:
Sass::SyntaxError: Invalid CSS after " *=require animate": expected "{", was ""

**Comment by ZakkMan** [comment]
@antebozic What's the link to the repo for your project?

**Comment by antebozic** [comment]
https://github.com/antebozic/habit_tracker

**Comment by ZakkMan** [comment]
Q & A from office hours:

1. Reoccurring events in Rails
* http://edgeguides.rubyonrails.org/active_job_basics.html
* https://launchschool.com/blog/cron-jobs-and-rails

2. Integrate with KickChart or some other charting library
* https://www.chartkick.com/
* `<table>`

3. Email verification and reminders:
* http://guides.rubyonrails.org/action_mailer_basics.html
