### ISSUE TITLE
WDI-20 Project 2 (Justin Probst)

### ISSUE THREAD

**Issue by probstin** [ga-dc/project2-gallery#235]
**Code**
Client: https://github.com/probstin/devj-client
API: https://github.com/probstin/devj-server

**Video**
Screencast: https://www.youtube.com/watch?v=fbdIunAIfcA&feature=youtu.be

**Heroku**
Client: https://developersjournalclient.herokuapp.com/home
API: https://developersjournal.herokuapp.com

**Comment by aspittel** [comment]
Awesome job! https://github.com/probstin/devj-server/pull/1
