### ISSUE TITLE
DC Brew Circuit: Julia Schultz

### ISSUE THREAD

**Issue by jschultz21** [ga-dc/project2-gallery#28]
YouTube: https://youtu.be/5r3OPSSgvDM
GitHub: https://github.com/jschultz21/dc-brew-circuit

**Comment by marasanders** [comment]
Makes me want to start drinking beer!!

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/jschultz21/dc-brew-circuit/pull/1)
