### ISSUE TITLE
Project 2 Submission: Where have you been? (Hyojin Sarchet)

### ISSUE THREAD

**Issue by hyojinsarchet** [ga-dc/project2-gallery#280]
Screencast: https://youtu.be/G1B_ytAdEhI
Github: https://github.com/hyojinsarchet/Where-have-you-been-
Heroku: https://sheltered-scrubland-75667.herokuapp.com/

**Comment by ZakkMan** [comment]
# Project Evaluation

## Hard Requirements

The following must be true of your project for it to be considered complete:

- [x] The app is deployed to Heroku
- [x] A screencast is included in the submission
- [x] A new repo with the student's project is included in the submission

## Evaluation Requirements

Your scores on the following evaluation requirements are based on the [Evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project2/blob/master/evaluation.md) for this project. You must achieve at least a 1 (progressing) for each category. 

### Technical Requirements

> **Your Score: Performing (3)**

It looks like you have full CRUD and meet the other technical requirements of the project. Additionally, really great work integrating it with a map! Something that I think would also help your app would be to add user authentication with Passport - then users can track where they've been (separate from other users). You could also consider integrating with a travel-related API!

### Creativity & Interface

> **Your Score: Performing (2)**

Your app looks great and the UI works really well. For more advanced functionality, consider making it responsive! 

### Code Quality

> **Your Score: Performing (2)**

Your controller is really clean and your code is well organized. Interesting choice to put the `models/` directory inside the `db/` directory - you'll see that a lot! I recommend being careful with naming, I don't know that `Been` is the best model name for what is really maybe a `Trip`. That's a small point though, overall your code is really well written!

### Functionality

> **Your Score: Performing (2)**

You've got a good amount of functionality here, including a nice map, and everything seems to be working without any errors. Really great job!

### Planning / Process / Submission

> **Your Score: Performing (2)**

Your user stories are well scoped and your mvp, bronze, silver and gold versions are all well drafted and seem achievable. It looks like you're missing a wireframe or some of the other planning things we asked for. Wireframes can really help you with the layout and design of your site, so you're not making those decisions while trying to code!

I've posted issues on your project repository with specific feedback and action items for you to consider. Your overall score on this project is 11. If you have any questions about my feedback, you can respond to that specific issue and I'll get back to you as soon as I can. I'm also happy to meet in person to discuss.

Great work!
