### ISSUE TITLE
Project 2 Grant Brown

### ISSUE THREAD

**Issue by grantnathanielbrown** [ga-dc/project2-gallery#292]
Repo:

https://github.com/grantnathanielbrown/Mangad

Screencast:

https://www.youtube.com/watch?v=niuO9BZyOIc

**Comment by ZakkMan** [comment]
Deployed version: https://mangad.herokuapp.com/

**Comment by ZakkMan** [comment]
# Project Evaluation

## Hard Requirements

The following must be true of your project for it to be considered complete:

- [x] The app is deployed to Heroku
- [x] A screencast is included in the submission
- [x] A new repo with the student's project is included in the submission

## Evaluation Requirements

Your scores on the following evaluation requirements are based on the [Evaluation rubric](https://git.generalassemb.ly/ga-wdi-exercises/project2/blob/master/evaluation.md) for this project. You must achieve at least a 1 (progressing) for each category. 

### Technical Requirements

> **Your Score: Excelling (3)**

Really great job on your project! I'm really impressed you got Auth working and it looks like that was one of the first things you tackled. It looks like you put a lot of work into this project and it really shows! 💪

### Creativity & Interface

> **Your Score: Performing (2)**

I really love the imagery and personal spin you threw on this, it looks great! I'd love to hear your thoughts on how bootstrap compares to materialize. 

### Code Quality

> **Your Score: Performing (2)**

Your code is generally well organized and well formatted. I suggest running it through a validator and working through the errors you get there. I've also given you some feedback on thinking through howyou organize your routes that you should take a look at to bring this to a 3. 

### Functionality

> **Your Score: Performing (2)**

With AUTH and CRUD it looks like you've got a lot of functionality here, all without any errors. If you want to bring this to a 3 you could tackle user uploads to S3 or expand the functionality to include some additional features like comments, liking images, grouping images into albums, etc. 

### Planning / Process / Submission

> **Your Score: Performing (2.5)**

Your planning process seems to be really thorough! Your user stories are all well scoped and it looks like you achieved at least your MVP. Did you make a wireframe?

I've posted issues on your project repository with specific feedback and action items for you to consider. Your overall score on this project is 11.5. If you have any questions about my feedback, you can respond to that specific issue and I'll get back to you as soon as I can. I'm also happy to meet in person to discuss.

Great work!
