### ISSUE TITLE
Matt Sharpe Cellar_Project2

### ISSUE THREAD

**Issue by mtsharpe** [ga-dc/project2-gallery#298]
Link to repo: https://github.com/mtsharpe/Cellar-Project-2/tree/master
Link to deployed app: https://ms-cellar.herokuapp.com/wines
Screencast: https://www.youtube.com/watch?v=KOPZfQzQd18&feature=youtu.be

Things you'd like specific feedback on: Insight/outline on next steps to incorporate unique users would be helpful. Any DRY code advice (CSS is a bit unwieldy) or tips for additional functionality.

**Comment by aspittel** [comment]
🎉 awesome job! Full feedback https://github.com/mtsharpe/Cellar-Project-2/pull/2
