### ISSUE TITLE
Project 2 - 2018 Candidate Explorer

### ISSUE THREAD

**Issue by jasonptoups** [ga-dc/project2-gallery#299]
Link to back end repo: https://github.com/jasonptoups/2018-candidates-backend
Link to front end repo: https://github.com/jasonptoups/2018-candidates-frontend
Link to deployed app: https://jasonptoups.github.io/2018-candidates-frontend/

Things you'd like specific feedback on:
I need help DRYing up the code in my script.js file, at the very end. There's a lot of comments there about it.

**Comment by jasonptoups** [comment]
Video link: https://vimeo.com/265632805

**Comment by aspittel** [comment]
👍 awesome job! full feedback: https://github.com/jasonptoups/2018-candidates-frontend/pull/1
