### ISSUE TITLE
Annabelle Taylor SEI2 project 2

### ISSUE THREAD

**Issue by annabelle-t-taylor** [ga-dc/project2-gallery#369]
Link to repo: https://github.com/annabelle-t-taylor/sororitree
Link to deployed app: https://sororitree.herokuapp.com/
Link to video: https://youtu.be/fnMTDSBUOHw

Things you'd like specific feedback on: I think I have a pretty decent understanding of the shortcomings/things that still need work on this project, but I'd be curious to hear if you have any feedback on the UI. I think it's pretty simple, but I'd like to know if it's intuitive for folks who may not have experience in the Greek system (or if it's...wait for it...all Greek to them).

**Comment by tomatohammado** [comment]
re: all Greek to <them>

[ha!](https://media.giphy.com/media/xiqoC9OnM7dju1YSe7/giphy.gif)
