### ISSUE TITLE
Paul Blake, WDI 28: Project 2 (Dive Log)

### ISSUE THREAD

**Issue by pnblake** [ga-dc/project2-gallery#377]
Link to repo: https://github.com/pnblake/dive-log-app
Link to deployed app: http://dive-log.pnblake.com

Things you'd like specific feedback on: (Will update)

**Comment by pnblake** [comment]
https://www.youtube.com/watch?v=qlchRsQnTM8

**Comment by pnblake** [comment]
@ZakkMan @tomatohammado Be sure to throw a 404.

**Comment by ZakkMan** [comment]
This is fantastic! I love it!
