### ISSUE TITLE
Leo Busenah Project2

### ISSUE THREAD

**Issue by busenah** [ga-dc/project2-gallery#386]
Production URL: 
Repository: https://github.com/busenah/Project2
Screencast:

Zakk, I was initially unable to deploy my project because i had it on the college github and not mine. One of the WDI 27 students helped me to transfer it to my github as I had no enough permissions to do that. I am still working on it and should be through by end of tomorrow. Thank you

**Comment by ZakkMan** [comment]
Leo, thanks for resubmitting. We'll send you our feedback soon.
