### ISSUE TITLE
Nwachukwu, Chiebuka (JSON API)

### ISSUE THREAD

**Issue by cenwachukwu** [ga-dc/project2-gallery#462]
Production (deployed) URL: https://med-directory-cen.herokuapp.com/directory
Repository: https://github.com/cenwachukwu/a-food-and-drug-api
Screencast:

Things you'd like specific feedback on:

**Comment by dcartist** [comment]
I'm having issues deleting a profile and the get. 
When going to this, I get an empty array
https://med-directory-cen.herokuapp.com/directory/profile/James

Look into everything so that it does full crud and make sure the documentation matches what is needed for full CRUD.
