### ISSUE TITLE
Igor Slabykh. Project 6: API Project

### ISSUE THREAD

**Issue by Cherezmz** [ga-dc/project2-gallery#476]
Production (deployed) URL: (
Repository: https://github.com/Cherezmz/jsonAPI 
Screencast:

Things you'd like specific feedback on: I created a json file with the data using axios and created connection and seed files but need more conceptual understanding of what to do next. I also did not deploy it

**Comment by dcartist** [comment]
So when posting ( I know it doesn't make sense to be able to add a new country but it should be there) I'm getting this message from the posting:
```
{
    "error": "Countries validation failed: name: The name is incorrect"
}
```
Also, you need to put a README, and deploy. Work through these and let me know when it's corrected. <img src="https://media.giphy.com/media/HFdZPf52z9x4s/giphy.gif"/>
