### ISSUE TITLE
Interactive Movie API Full Stack Site

### ISSUE THREAD

**Issue by mdrisco4** [ga-dc/project2-gallery#477]
Production (deployed) URL:  Heroku account made, need to figure out how to deploy 2 repos(front and back end)
Repository: backend:    https://github.com/mdrisco4/JSON-API-Build
                      frontend:    https://github.com/mdrisco4/json_api_build_fe
Screencast:

Things you'd like specific feedback on: Code dryness and feature utility/suggestions

**Comment by dcartist** [comment]
Continue to work on making this API functional. You are very close. Also, there needs to be a README, and work on deployment. Let me know when this is fixed. You can do this!

<img src="https://www.all-about-psychology.com/images/bobo.gif"/>
