### ISSUE TITLE
Jose [API-project]

### ISSUE THREAD

**Issue by jcasado6** [ga-dc/project2-gallery#478]
Production (deployed) URL: https://glacial-sierra-45848.herokuapp.com/
Repository: https://github.com/jcasado6/api-project

Things you'd like specific feedback on: Anything and everything

**Comment by jcasado6** [comment]
updated deployed URL: https://brewery-tracker-api.herokuapp.com/breweries

**Comment by dcartist** [comment]
As strange as it sounds, when using heroku to POST, I get this message"
{
    "breweries": "brewery added!"
}

but when looking at the API it only shows the ID but no information was pushed into it. This is a great README. 
Notify me when there is a solution for this part. 

<img src="https://www.all-about-psychology.com/images/bobo.gif"/>
