### ISSUE TITLE
Kelly - Api

### ISSUE THREAD

**Issue by K0LdW0rLd** [ga-dc/project2-gallery#479]
Production (deployed) URL:  https://studio-ghibli-970.herokuapp.com/studio
Repository: https://github.com/K0LdW0rLd/studio-ghibli
Screencast:

Things you'd like specific feedback on:
The search component shows all api names instead of one searching.

**Comment by dcartist** [comment]
For the API, I would need a link to the repo of the backend. Also, there needs to be a README about the project. 
Let me know when this part is done. 

<img src="https://www.all-about-psychology.com/images/bobo.gif"/>
