### ISSUE TITLE
Dhaesha Horoscope API

### ISSUE THREAD

**Issue by CodeDrip** [ga-dc/project2-gallery#480]
Production (deployed) URL:
Repository: https://git.generalassemb.ly/Dhaesha/horoscope-api
Screencast:

Things you'd like specific feedback on:

Not at the moment.

**Comment by dcartist** [comment]
Do you have this set to private, because it's not showing on my computer. Check through the settings and let me know!

![image](https://user-images.githubusercontent.com/21227957/72092679-cfe25080-32e0-11ea-94ce-7c06e9f5f27b.png)
