### ISSUE TITLE
Dilmurod Bukharov Project-6

### ISSUE THREAD

**Issue by dilmurodb** [ga-dc/project2-gallery#481]
Production (deployed) URL:
Repository:https://github.com/dilmurodb/project-6
Screencast:

Things you'd like specific feedback on:

**Comment by dcartist** [comment]
We already talked, make sure to have a README and Continue to work on your api and let me know when this is done!
<img src="https://media1.tenor.com/images/52075754258fc5b329a8f37d87a0b285/tenor.gif?itemid=4821159"/>
