### ISSUE TITLE
api-project-6

### ISSUE THREAD

**Issue by D-Riv** [ga-dc/project2-gallery#495]
Production (deployed) URL: https://api-project-6.herokuapp.com/index
Repository: https://github.com/D-Riv/api-project-6
Screencast: https://www.youtube.com/watch?v=YYRkuB01M6w&feature=youtu.be

Things you'd like specific feedback on: Feedback on folder structure and utilizing routes and controllers properly. I tried a method closer to what we did during the bachelors lab.

**Comment by D-Riv** [comment]
@ZakkMan

**Comment by 0xZakk** [comment]
@D-Riv It looks like only the index route works and there's now way to get a single document by it's ID?

**Comment by D-Riv** [comment]
Hey @ZakkMan all routes are working on my end i updated the readme to better reflect the routes. I did not include an ID route just routes for finding a show with a particular rating, network, and show. Also updated screencast.

**Comment by D-Riv** [comment]
Production (deployed) URL: https://tv-movie-api.herokuapp.com/
Repository: https://github.com/D-Riv/tv-movie-api
Updated api @ZakkMan

**Comment by 0xZakk** [comment]
@D-Riv This looks great! Great work!
