### ISSUE TITLE
Project 2 Submission

### ISSUE THREAD

**Issue by mikeflores** [ga-dc/project2-gallery#73]
[Project Repo](https://github.com/mikeflores/heimdall)
- Also in Repo: [Try Heimdall](https://tryheimdall.herokuapp.com/)  & [Video Demo](https://vimeo.com/188139217)

comfort: 3
completeness: 2

**Comment by jshawl** [comment]
https://gist.github.com/jshawl/a97ad127baf63534ac9d944a3743b4a6 👍
