### ISSUE TITLE
Oki Project 2 - The Phantoms

### ISSUE THREAD

**Issue by nickoki** [ga-dc/project2-gallery#74]
[GitHub Repo](https://github.com/nickoki/phantoms)

[Video Demo](https://youtu.be/9pF69se86iw)

ERD
![image](https://cloud.githubusercontent.com/assets/15880182/19566258/9b1d05de-96b7-11e6-86f4-214895b9a1ca.png)

**Comment by nolds9** [comment]
:+1: Please see feedback [here](https://github.com/nickoki/phantoms/pull/1)
