### ISSUE TITLE
Project-2 cookbook

### ISSUE THREAD

**Issue by manishP33** [ga-dc/project2-gallery#84]
video presentation = https://www.youtube.com/watch?v=_XZP3XtxdpY

github = https://github.com/manishP33/CookBookJunction/tree/gh-pages

heroku = https://manishcookbook.herokuapp.com/
( have to fix Procfile)

**Comment by jshawl** [comment]
👍 https://gist.github.com/jshawl/ae235138abc42bd7c4b3c6241b9abbfc
