### ISSUE TITLE
Andrew Whitley - Project Two - Agora

### ISSUE THREAD

**Issue by AWhitleyGA** [ga-dc/project2-gallery#85]
GitHub repository - https://github.com/AWhitleyGA/agora

Hosted App (Heroku) - https://project-two-agora.herokuapp.com/

YouTube Video - https://youtu.be/fkEwSoRezus

**Comment by jshawl** [comment]
👍 https://gist.github.com/jshawl/92fdedb11b24011d2fd86230531db82e
